// Site Configuration — Generated by Polaris Point Admin
// Template: plumber | Theme: Professional
window.SITE_CONFIG = {

  // === THEME (Professional — Navy & Orange) ===
  theme: {
    primary: "#1B3A6B",
    primaryDark: "#0f2748",
    accent: "#E8601E",
    accentLight: "#FF7A3D",
    bg: "#f6f8fc",
    text: "#173052",
    muted: "rgba(23,48,82,.55)",
    fontHeading: "'Montserrat', sans-serif",
    fontBody: "'Source Sans 3', sans-serif",
    logoUrl: ""
  },

  // === PAGE META ===
  pageTitle: "Allen & Sons Plumbing | CA 94605",
  metaDescription: "Allen & Sons Plumbing offers fast, reliable service. Licensed and insured.",

  // === IDENTITY ===
  businessName: "Allen & Sons Plumbing",
  businessNameShort: "Allen &",
  licenseNumber: "",

  // === CONTACT ===
  phone: "(510) 726-8100",
  phoneTelHref: "tel:+15107268100",
  email: "info@example.com",
  emailHref: "mailto:info@example.com",
  address: "7645 MacArthur Blvd, Oakland, CA 94605, USA",
  hours: "Monday: Open 24 hours | Tuesday: Open 24 hours | Wednesday: Open 24 hours | Thursday: Open 24 hours | Friday: Open 24 hours | Saturday: Open 24 hours | Sunday: Open 24 hours",

  // === TOPBAR ===
  topbarText: "24/7 Emergency Service Available",

  // === HERO ===
  heroHeadline: "Allen & Sons Plumbing",
  heroSubtext: "Licensed & insured plumber proudly serving CA 94605 and surrounding areas. Rated 4.8 stars by 138+ customers. Call today for a free estimate.",
  heroImage: "/api/photo?ref=Ab43m-vQYB9iuhfNDpsArOygHZnbTGsbJpMnX-dBxbA9XkAnb1w18dEaD_KV8zLM86nY-SuvEXAO4O-SzeQZVZDlDh8_FxtZ9X6oiZ82LbSlRFEth3ukjiJRN7ZbqYJLmP3Kbs-wLxkHOFnVpIUTBtZUfqKHegl6bIMxTIBhzMIZU7W74cPxRASiBg_EwUCDioTSuzt80DrX9xlPRL-sCt0iPKNG5lJ_JCrCKyWxMclcQLjisx_TrTWeZC5a316Dv2gudozTZXEv0X9qauB3Sj7p6XWK8KZ724twCZJILVYHbRWMOQHdZc5fEgjqpjyHq1lcO-qW7sidcsJUt9U8hm2etg4gwR0qkeXmJGAJ9JSPGWk0doqBA7phQaoyVr8Ez0IkSzqmtYp3oAmxtyth5E6uisa6YnjEdwrO8KBTqSU1KFP4QSH6NWccyVZ8Q0qNPQ&maxwidth=800",
  heroImageAlt: "Allen & Sons Plumbing - professional service",
  heroCta1: "Call (510) 726-8100",
  heroCta2: "Get a Free Estimate",

  // === TRUST BADGES ===
  trustBadge1: "Licensed & Insured",
  trustBadge2: "5-Star Rated",
  trustBadge3: "Locally Owned",
  trustBadge4: "10+ Years Experience",

  // === SERVICES ===
  servicesLabel: "What We Do",
  servicesTitle: "Our Services",
  service1Name: "Drain Cleaning",
  service1Desc: "Clogged drains fixed quickly with professional-grade hydro-jetting and cable equipment.",
  service2Name: "Water Heater Repair",
  service2Desc: "Repair or upgrade your tank or tankless water heater for reliable hot water every day.",
  service3Name: "Leak Detection",
  service3Desc: "Find hidden leaks fast with electronic detection equipment and prevent expensive damage.",
  service4Name: "Fixture Repair",
  service4Desc: "Stop constant drips and running toilets with lasting faucet, toilet, and fixture repairs.",
  service5Name: "Pipe Installation",
  service5Desc: "New pipe installs and whole-house re-pipes built for code compliance and long-term flow.",

  // === ABOUT ===
  aboutImage: "/api/photo?ref=Ab43m-vOquu_ScrYChEXW5_q64temsEejlCOfj3nFTGGPNax1EOtapbRu7SN4cTVfymsb1TAmAWp2ZUNFqi_H2SHArFfwu1S8FGIVw92pi-do8MYKm92vX9rQzncrCtDLbBj5CFayaW3CH5A6sSU8Ia7bY-2OmVES9llCbo9iId44egpabMevc0TGdsjEyUNAGwlrFsUt-4W9eOl7fUzkHzxUZ-MoP1OPDtZ4_WCMneAY5F6EcsGtI3YKxXjNiN_l8-fwQ70kfbRZhcxQk7Mu10RKz6Xl4Z6wW8lP38SDVDKPguK_OELYw-mtkwgsUqbNwmHOtjB3tu58KoqrXkOJtvoH3MKsy0mIFqy0gaP0NtL_zcClE5-VM9js4KGVDo8czd_NFDAMBxqIM_67rEWcUku_XAa1rNteZiKDUiOpILYqFyd4SljJSlJs0LxizJs8gR-&maxwidth=800",
  aboutImageAlt: "Allen & Sons Plumbing team",
  aboutLabel: "Why Choose Us",
  aboutTitle: "CA 94605 Trusts Allen &",
  aboutText: "Allen & Sons Plumbing has been serving CA 94605 with reliable, professional plumber services. With a 4.8-star rating from 138 customers, we take pride in quality work and honest pricing. Every job is treated with care and respect.",

  // === WHY CARDS ===
  why1Title: "Same-Day Service",
  why1Text: "Most calls handled the same day.",
  why2Title: "Upfront Pricing",
  why2Text: "Clear quotes before work starts. No surprise fees.",
  why3Title: "Satisfaction Guaranteed",
  why3Text: "If the problem comes back, so do we.",

  // === REVIEWS ===
  reviewsLabel: "Testimonials",
  reviewsTitle: "What Our Customers Say",
  reviews: [
    {
      text: "i'm really happy with my new plumber in oakland. after moving here from far away, it was tough to find reliable plumbing help. i called and cory set up a visit for a morning later that week since it wasn't urgent. he explained the best way to repair both of my showers and gave a fair estimate. they returned with the right parts and even updated the water line to my fridge so i could install a water filter. cory also gave me some great advice about my well. if you need a plumber, definitely give them a try—you won't be disappointed.",
      attribution: "Jesus Todd &middot; 3 months ago",
      rating: 5
    },
    {
      text: "After my basement in Oakland got flooded, my water heater stopped working. I called a local plumbing service, and Roman was the plumber who helped me out. Roman was really friendly and took the time to explain all my options for getting the water heater fixed or replaced. He answered every question I had and gave me plenty of helpful information. Communication was fast and clear, which made everything so much easier. Deciding to hire them for the installation was simple. Roman and his team showed up on time and got the new water heater installed quickly and professionally. Now, my hot water is running perfectly, and I’m very happy with their top-notch service. If you need a trustworthy plumber in Oakland, I definitely recommend this team!",
      attribution: "Jack Mooney &middot; 4 months ago",
      rating: 5
    },
    {
      text: "Two plumbers from Allen & Sons Plumbing came out to my home in Oakland. The first plumber, Cory, was friendly and professional. He took his time to explain everything and needed to leave briefly to pick up some additional parts for the job. I was very impressed with the attention to detail and the high level of service. Later, Roman came by to fix a small leak, and I have to say, he was truly outstanding. Roman was personable, efficient, and shared a lot of helpful information about my home’s plumbing and what maintenance I might need in the future. Out of all the plumbers I’ve worked with, he stands out as the best. The service I received was excellent from start to finish. I plan to use this company for all my plumbing needs as long as I live in Oakland. If you need a trustworthy, knowledgeable plumber, I highly recommend asking for Roman!",
      attribution: "Natasha Hinton &middot; 4 months ago",
      rating: 5
    },
    {
      text: "Cory was a fantastic plumber and a real pro when it came to replacing our power vent water heater in Oakland. He didn’t just swap out the old water heater—he also fixed a gas line that had been poorly installed by someone else before. I’m really grateful that Cory noticed the problem with the gas line and made sure everything was safe and up to code. Now, I feel lucky to have found a trustworthy and dependable plumber who does the job right the first time. I would absolutely recommend Cory to anyone needing plumbing work, because he’s not only skilled but also friendly and offers fair prices. Great service all around!",
      attribution: "Jayla Acosta &middot; 4 months ago",
      rating: 5
    },
    {
      text: "After being assigned a different plumber by my home warranty company who couldn't solve my plumbing problem, I was then referred to Allen & Sons Plumbing, and I couldn't be happier with the service I received. Roman arrived and spent several hours carefully working on my pipes, tackling issues that had clearly built up over many years. Throughout the visit, he explained each step and answered all my questions, making sure I understood what was happening. He was very respectful of my home, keeping everything clean as he worked. By the end, my drains were running better than they have in a very long time. Even though the arrival wasn't exactly on schedule, the quality of work and professionalism more than made up for it. I highly recommend their plumbing services to anyone needing expert help.",
      attribution: "Gage Jefferson &middot; 5 months ago",
      rating: 5
    }
  ],

  // === SERVICE AREA ===
  serviceAreaLabel: "Coverage Area",
  serviceAreaTitle: "Serving CA 94605 & Surrounding Areas",
  serviceAreaText: "",
  serviceAreaImage: "/api/photo?ref=Ab43m-vOquu_ScrYChEXW5_q64temsEejlCOfj3nFTGGPNax1EOtapbRu7SN4cTVfymsb1TAmAWp2ZUNFqi_H2SHArFfwu1S8FGIVw92pi-do8MYKm92vX9rQzncrCtDLbBj5CFayaW3CH5A6sSU8Ia7bY-2OmVES9llCbo9iId44egpabMevc0TGdsjEyUNAGwlrFsUt-4W9eOl7fUzkHzxUZ-MoP1OPDtZ4_WCMneAY5F6EcsGtI3YKxXjNiN_l8-fwQ70kfbRZhcxQk7Mu10RKz6Xl4Z6wW8lP38SDVDKPguK_OELYw-mtkwgsUqbNwmHOtjB3tu58KoqrXkOJtvoH3MKsy0mIFqy0gaP0NtL_zcClE5-VM9js4KGVDo8czd_NFDAMBxqIM_67rEWcUku_XAa1rNteZiKDUiOpILYqFyd4SljJSlJs0LxizJs8gR-&maxwidth=800",
  serviceAreaImageAlt: "Serving CA 94605",
  serviceAreas: ["CA 94605"],

  // === CONTACT FORM ===
  contactLabel: "Get In Touch",
  contactTitle: "Request Your Free Estimate",
  contactText: "Fill out the form and we will get back to you within 2 hours during business hours.",
  formServiceOptions: ["Drain Cleaning","Water Heater Repair","Leak Detection","Fixture Repair","Pipe Installation","Other"],

  // === CTA BANNER ===
  ctaTitle: "Need Help Right Now?",
  ctaText: "Our team is available to help you today.",
  ctaButton: "Call (510) 726-8100",

  // === FOOTER ===
  footerDescription: "Allen & Sons Plumbing. Licensed, insured, and committed to getting the job done right.",
  footerLegal: "&copy; 2026 Allen & Sons Plumbing. All rights reserved.",
  footerServices: ["Drain Cleaning","Water Heater Repair","Leak Detection","Fixture Repair","Pipe Installation"],

  // === FEATURE FLAGS ===
  features: {
    mobileNav: true,
    activeNavHighlight: true,
    stickyHeader: true,
    smoothScroll: true,
    formHandling: true,
    scrollReveal: true,
    reviewCarousel: true,
    googleReviewsBadge: true,
    floatingButtons: true,
    stickyBottomCta: true,
    exitIntent: true,
    urgencyBanner: true,
    faqAccordion: true,
    serviceAreaMap: true,
    lightbox: true,
    teamModals: false,
    blogPreview: true,
    cookieConsent: true,
    trustBar: true,
    analytics: false
  },

  // === GOOGLE REVIEWS ===
  googleReviewsRating: "4.8",
  googleReviewsCount: "138",
  googleReviewsUrl: "https://maps.google.com/?cid=1764127034643314596",

  // === ENGAGEMENT ===
  smsNumber: "5107268100",
  whatsappNumber: "",
  calcomUrl: "",

  exitIntent: {
    headline: "Wait — Get $50 Off Your First Service",
    text: "Book your service today and save. New customers only.",
    cta: "Claim My Discount",
    ctaUrl: "#contact"
  },

  urgencyBanner: {
    text: "Limited Time Offer — Call today for a free estimate",
    endDate: "2026-12-31"
  },

  // === FAQ ===
  faqs: [
  ],

  // === SERVICE AREA MAP ===
  googleMapsEmbed: "https://www.google.com/maps?q=7645%20MacArthur%20Blvd%2C%20Oakland%2C%20CA%2094605%2C%20USA&output=embed",

  // === BLOG POSTS ===
  blogPosts: [
  ],

  team: [
  ],

  // === TRUST BAR LOGOS ===
  trustLogos: [
    { src: "", alt: "Licensed & Insured" },
    { src: "", alt: "BBB A+ Rated" },
    { src: "", alt: "Google Guaranteed" }
  ],

  // === SEO ===
  canonicalUrl: "",
  ogImage: "",
  geoRegion: "",
  geoPlacename: "CA 94605",
  geoPosition: "",
  schema: {
    type: "LocalBusiness",
    additionalType: "",
    priceRange: "$$",
    foundingDate: "",
    areaServed: ["CA 94605"],
    openingHours: []
  },

  // === ANALYTICS ===
  analytics: {
    ga4Id: "",
    metaPixelId: "",
    hotjarId: "",
    clarityId: ""
  },

  // === COOKIE CONSENT ===
  cookieConsent: {
    text: "We use cookies to improve your experience and analyze site traffic.",
    acceptButton: "Accept",
    declineButton: "No Thanks",
    privacyUrl: "#"
  },

  // === CHATBOT (disabled — toggle off in builder) ===
  chatbot: { enabled: false },

  // === BRAND VOICE ===
  // Shapes AI-composed copy AND folds into the chatbot system prompt.
  brand: {
    targetCustomer: "",
    differentiators: [],
    voiceNotes: ""
  },

  // === OPS / NOTIFICATIONS (all tiers) ===
  // Lead routing + report recipient. Consumed by /api/site-lead.js
  // and the monthly reporting cron.
  ops: {
    leadEmail: "",
    leadCcEmail: "",
    leadAlertCadence: "instant",
    reportEmail: "",
    ownerNotes: ""
  }
};
